/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BuiltRouteImport } from './routes/built'
import { Route as DeckRouteImport } from './routes/deck'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as EmbeddedArchitectRouteImport } from './routes/embedded-architect'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as LivingPolicyRouteImport } from './routes/living-policy'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BuiltRoute = BuiltRouteImport.update({
  id: '/built',
  path: '/built',
  getParentRoute: () => rootRouteImport,
} as any)
const DeckRoute = DeckRouteImport.update({
  id: '/deck',
  path: '/deck',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const EmbeddedArchitectRoute = EmbeddedArchitectRouteImport.update({
  id: '/embedded-architect',
  path: '/embedded-architect',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LivingPolicyRoute = LivingPolicyRouteImport.update({
  id: '/living-policy',
  path: '/living-policy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/built': typeof BuiltRoute
  '/deck': typeof DeckRoute
  '/documents': typeof DocumentsRoute
  '/embedded-architect': typeof EmbeddedArchitectRoute
  '/how-it-works': typeof HowItWorksRoute
  '/living-policy': typeof LivingPolicyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/built': typeof BuiltRoute
  '/deck': typeof DeckRoute
  '/documents': typeof DocumentsRoute
  '/embedded-architect': typeof EmbeddedArchitectRoute
  '/how-it-works': typeof HowItWorksRoute
  '/living-policy': typeof LivingPolicyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/built': typeof BuiltRoute
  '/deck': typeof DeckRoute
  '/documents': typeof DocumentsRoute
  '/embedded-architect': typeof EmbeddedArchitectRoute
  '/how-it-works': typeof HowItWorksRoute
  '/living-policy': typeof LivingPolicyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/built'
    | '/deck'
    | '/documents'
    | '/embedded-architect'
    | '/how-it-works'
    | '/living-policy'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/built'
    | '/deck'
    | '/documents'
    | '/embedded-architect'
    | '/how-it-works'
    | '/living-policy'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/built'
    | '/deck'
    | '/documents'
    | '/embedded-architect'
    | '/how-it-works'
    | '/living-policy'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BuiltRoute: typeof BuiltRoute
  DeckRoute: typeof DeckRoute
  DocumentsRoute: typeof DocumentsRoute
  EmbeddedArchitectRoute: typeof EmbeddedArchitectRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LivingPolicyRoute: typeof LivingPolicyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/built': {
      id: '/built'
      path: '/built'
      fullPath: '/built'
      preLoaderRoute: typeof BuiltRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deck': {
      id: '/deck'
      path: '/deck'
      fullPath: '/deck'
      preLoaderRoute: typeof DeckRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/embedded-architect': {
      id: '/embedded-architect'
      path: '/embedded-architect'
      fullPath: '/embedded-architect'
      preLoaderRoute: typeof EmbeddedArchitectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/living-policy': {
      id: '/living-policy'
      path: '/living-policy'
      fullPath: '/living-policy'
      preLoaderRoute: typeof LivingPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BuiltRoute: BuiltRoute,
  DeckRoute: DeckRoute,
  DocumentsRoute: DocumentsRoute,
  EmbeddedArchitectRoute: EmbeddedArchitectRoute,
  HowItWorksRoute: HowItWorksRoute,
  LivingPolicyRoute: LivingPolicyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
